config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :skills
  resources :user_steps

  root to: 'skills#landing'
  get '/about', to: 'skills#about', as: 'about'
  get '/profile', to: 'skills#profile', as: 'profile'
  get '/profile', to: 'skills#profile', as: 'user_root'
  get '/results', to: 'skills#results', as: 'results'
  get '/public_profile/:id', to: 'skills#publicprofile', as: 'public_profile'

end

#      Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        registrations#cancel
#        user_registration POST   /users(.:format)               registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       registrations#new
#   edit_user_registration GET    /users/edit(.:format)          registrations#edit
#                          PATCH  /users(.:format)               registrations#update
#                          PUT    /users(.:format)               registrations#update
#                          DELETE /users(.:format)               registrations#destroy
#                   skills GET    /skills(.:format)              skills#index
#                          POST   /skills(.:format)              skills#create
#                new_skill GET    /skills/new(.:format)          skills#new
#               edit_skill GET    /skills/:id/edit(.:format)     skills#edit
#                    skill GET    /skills/:id(.:format)          skills#show
#                          PATCH  /skills/:id(.:format)          skills#update
#                          PUT    /skills/:id(.:format)          skills#update
#                          DELETE /skills/:id(.:format)          skills#destroy
#               user_steps GET    /user_steps(.:format)          user_steps#index
#                          POST   /user_steps(.:format)          user_steps#create
#            new_user_step GET    /user_steps/new(.:format)      user_steps#new
#           edit_user_step GET    /user_steps/:id/edit(.:format) user_steps#edit
#                user_step GET    /user_steps/:id(.:format)      user_steps#show
#                          PATCH  /user_steps/:id(.:format)      user_steps#update
#                          PUT    /user_steps/:id(.:format)      user_steps#update
#                          DELETE /user_steps/:id(.:format)      user_steps#destroy
#                     root GET    /                              skills#landing
#                    about GET    /about(.:format)               skills#about
#                  profile GET    /profile/:id(.:format)         skills#profile
#                user_root GET    /profile(.:format)             skills#profile
#                  results GET    /results(.:format)             skills#results
# Jasons-MacBook-Pro-3:tradecraft jason$ rake routes
#                   Prefix Verb   URI Pattern                    Controller#Action
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        registrations#cancel
#        user_registration POST   /users(.:format)               registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       registrations#new
#   edit_user_registration GET    /users/edit(.:format)          registrations#edit
#                          PATCH  /users(.:format)               registrations#update
#                          PUT    /users(.:format)               registrations#update
#                          DELETE /users(.:format)               registrations#destroy
#                   skills GET    /skills(.:format)              skills#index
#                          POST   /skills(.:format)              skills#create
#                new_skill GET    /skills/new(.:format)          skills#new
#               edit_skill GET    /skills/:id/edit(.:format)     skills#edit
#                    skill GET    /skills/:id(.:format)          skills#show
#                          PATCH  /skills/:id(.:format)          skills#update
#                          PUT    /skills/:id(.:format)          skills#update
#                          DELETE /skills/:id(.:format)          skills#destroy
#               user_steps GET    /user_steps(.:format)          user_steps#index
#                          POST   /user_steps(.:format)          user_steps#create
#            new_user_step GET    /user_steps/new(.:format)      user_steps#new
#           edit_user_step GET    /user_steps/:id/edit(.:format) user_steps#edit
#                user_step GET    /user_steps/:id(.:format)      user_steps#show
#                          PATCH  /user_steps/:id(.:format)      user_steps#update
#                          PUT    /user_steps/:id(.:format)      user_steps#update
#                          DELETE /user_steps/:id(.:format)      user_steps#destroy
#                     root GET    /                              skills#landing
#                    about GET    /about(.:format)               skills#about
#                  profile GET    /profile(.:format)             skills#profile
#                user_root GET    /profile(.:format)             skills#profile
#                  results GET    /results(.:format)             skills#results
#           public_profile GET    /public_profile/:id(.:format)  skills#publicprofile

app/models/skill.rb
class Skill < ActiveRecord::Base

  belongs_to :user

  def self.search(search)
    if search
      q = "%#{search}%"
      where('skill LIKE ?',q)
    else
      scoped
    end
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def landing
    #landing page
  end

  def about
    #how it works page
  end

  def profile
    @current_user = current_user
    @skill = @current_user.skills.new
    @user_skill = @current_user.skills.all
  end

  def publicprofile
    @user = User.find(params[:id])
    @user_skill = @user.skills.all
    render "public_profile"
  end

  def index
    # doing a search on this page
  end

  def results
    @current_user = current_user
    @skills = Skill.search(params[:search])
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @current_user = current_user
    @skill = @current_user.skills.new
  end

  def create
    @skill = Skill.create(skill_params)
    redirect_to profile_path
    # @skill = Skill.new(skill_params)

    # respond_to do |format|
    #   if @skill.save
    #     format.json { render json: @skill, status: :created}
    #     format.html {redirect_to profile_path}
    #   else
    #     format.json { render json: @skill.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    @skill.update(skill_params)
    redirect_to about_path
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to about_path
  end

  private
    def skill_params
      params.require(:skill).permit(:skill, :tolearn, :user_id, :tag, :learntag )
    end

end

app/helpers/skills_helper.rb
module SkillsHelper
  def distance_to_zipcode zipcode
    response = Typhoeus.get("https://zipcodedistanceapi.redline13.com/rest/#{ENV['ZIPCODE_KEY']}/distance.json/#{@current_user.zipcode}/#{zipcode}/miles")
    zipcode = JSON.parse(response.body)
    "#{zipcode["distance"].round(2)} miles"
  end 
end

app/views/skills/about.html.erb
<% content_for :body_type do%>
  aboutpage
<% end %>


<div class="container-about">
<br>
<h1 style="text-align:center">How it Works</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6" id="left_grid_landing">
      <h3 style="text-align:center"> Learn a skill  </h3>
      <p> TradeCrafts is dedicated to the idea of continual self-improvement and the idea that we are never the final product of ourselves. </p>
      <p> Therefore, TradeCrafts serves to act as a platform to connect like-minded people and help you achieve your next goal. </p>
      <p> Search from the many users to find a skill that you have always wanted to learn. </p>
      <p> Then let the connecting and learning begin! </p>
    </div>
    <div class="col-md-6" id="right_grid_landing">
      <h3 style="text-align:center"> Teach a skill </h3>
      <p> A true open source community can't only have students, it needs teachers as well. </p>
      <p> People from different walks of life, can teach whatever skill they have- you will be surprised who wants to learn what you know! </p>
      <p> Someone can request to connect with you to learn the skill you have, and they in turn may have something you want to learn! </p>
      <p> We believe that anyone and everyone can be a teacher! </p>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-md-3" id="melissa">
      <h3>Learn an instrument</h3>
      <img class="profile_pic" src="http://i.imgur.com/4gwJQJs.jpg" />
      <h4> Melissa Lee </h4>
      <p> Learned how to play piano </p>
    </div>
    <div class="col-md-3" id="frank">
      <h3>Learn to design</h3>
      <img class="profile_pic" src="http://i.imgur.com/AxEnZHy.jpg">
      <h4> Frank Chun </h4>
      <p> Learned how to use photoshop </p>
    </div>
    <div class="col-md-3" id="sarah">
      <h3>Learn languages </h3>
      <img class="profile_pic" src="http://i.imgur.com/qtZq40A.jpg">
      <h4> Sarah Morgan </h4>
      <p> Learned how to speak French  </p>
    </div>
    <div class="col-md-3" id="john">
      <h3>Learn to code</h3>
      <img class="profile_pic" src="http://i.imgur.com/h64F8HR.jpg">
      <h4> John Rodriguez </h4>
      <p> Learned how to code in Javascript </p>
    </div>
  </div>
</div>

<br>
<br>
</div>

app/views/skills/edit.html.erb
<h1>New Skill</h1>
<%= form_for @skill, :html => {:id => "new_skill"} do |f|%>
<%= f.label :bio %>
<%= f.text_field :bio %>
<%= f.label :skills %>
<%= f.text_field :skills%>
<%= f.label :tolearn %>
<%= f.text_field :tolearn %>
<%= f.submit%>
<% end %>

app/views/skills/index.html.erb
<% content_for :body_type do%>
  searchpage
<% end %>
<h1></h1>

<div id="searchform">
	<!-- hate doing these breaks, but the css won't work 
	on this page for some reason -->
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<h1 style="text-align:center">Search For Skills</h1>


<div class="col-md-4 col-md-offset-4">
<%= form_tag results_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], :class => 'form-control' %>
    <br>
    <%= submit_tag "Search", :skill => nil, :class => 'btn btn-default' %>
  </p>
<% end %>
</div>
</div>

app/views/skills/landing.html.erb
<% content_for :body_type do%>
  landingpage
<% end %>

<div class="landingcontainer">
  <img src="http://i.imgur.com/b7wxn7a.png" id="logo_landing" />
  
  <div id="block">
    <h2 class="landingtext" style="color:white"> Learn anything from anyone. </h2>
    <p>
      <a class="btn btn-success btn-lg" href="/users/sign_up">Sign Up</a>
      <span><a class="btn btn-success btn-lg" href="/about">Learn More</a></span>
    </p>
  </div>
</div>
<!-- <div class="jumbotron">
  <img src="http://i.imgur.com/b7wxn7a.png" id="tclogo" />
  <div id="block">
    <h2 class="landingtext"> Learn anything from anyone. </h2>
    <p><a class="btn btn-success btn-lg" href="/about">Learn more</a></p>
  </div>
</div> -->

app/views/skills/new.html.erb
<% content_for :body_type do%>
  newpage
<% end %>

<br>
<h1 style="color:white" class="col-md-4 col-md-offset-4">What are your skills?</h1>
	<%= bootstrap_form_for @skill, :html => {:id => "new_skill"} do |f|%>

<h3 style="color:white" class="col-md-4 col-md-offset-4">Category:</h3>
<div class="col-md-4 col-md-offset-4">
	<%= f.select :tag, options_for_select([["Art", "art"], ["Culinary", "culinary"], ["Language", "language"], ["Mechanical", "mechnical"], ["Music", "music"], ["Programming", "programming"], ["Sports", "sports"], ["Misc.", "misc."]], @skill.tag), hide_label: true %>
</div>

<div class="col-md-4 col-md-offset-4">
<%= f.label :skill, 'What are your skills?' %> 
	<%= f.text_field :skill, placeholder: 'Painting, singing, cooking...', hide_label: true%>
</div>

<h1 style="color:white" class="col-md-4 col-md-offset-4">What do you want to learn?</h1>

<h3 style="color:white" class="col-md-4 col-md-offset-4">Category:</h3>
<div class="col-md-4 col-md-offset-4">
	<%= f.select :learntag, options_for_select([["Art", "art"], ["Culinary", "culinary"], ["Language", "language"], ["Mechanical", "mechnical"], ["Music", "music"], ["Programming", "programming"], ["Sports", "sports"], ["Misc.", "misc."]], @skill.tag), hide_label: true %>
</div>

<div class="col-md-4 col-md-offset-4">
	<%= f.label :tolearn, 'What do you want to learn?' %>
	<%= f.text_field :tolearn, placeholder: 'Basketball, programming, spanish...', hide_label: true %>
</div>
	<%= f.hidden_field :user_id, value: current_user.id %>
<div class="col-md-4 col-md-offset-4">
	<%= f.submit "Submit"%>
</div>
<% end %>

app/views/skills/profile.html.erb
<% content_for :body_type do%>
  userprofile
<% end %>

<div class="profilejumbotron">
	<div id="profilepicture">
		<img src="<%= @current_user.pic%>" class="circular" />
	</div>
</div>

<div class="profilepagecontainer">
<div class="profileinfo">
	<h1 style="color:white"><%= current_user.username.capitalize %></h1>
	<h3 style="color:white"> Lives in <%= current_user.zipcode.to_region%> </h3 style="color:white"s>
	<h4 style="color:white"> Contact: <%= current_user.email %></h4>
	<%= link_to "Add Skill", new_skill_path, :class => 'btn btn-default' %>
</div>

<div class="col-md-6 col-md-offset-4" id="profilebio">
	<h1 style="color:white">Bio:</h1> <p style="color:white"><%= @current_user.bio %></p>
		<h1 style="color:white"><%= current_user.username.capitalize %>'s Skills:</h1>
	<ul>
	  <% @user_skill.each do |s| %>
	    <li><h4 style="color:white"><b><%= s.tag.upcase %></b>: <%=s.skill.capitalize%></h4>
	   	</li> 
	  <% end %>
	</ul>
		<h1 style="color:white"><%= current_user.username.capitalize %> wants to learn:</h1>
	<ul>
	  <% @user_skill.each do |s| %>
	    <li><h4 style="color:white"><b><%= s.learntag.upcase %></b>: <%=s.tolearn.capitalize %></h4></li>
	  <% end %>
	</ul>
</div>
</div>

</div>

app/views/skills/public_profile.html.erb
<% content_for :body_type do%>
  publicprofile
<% end %>

<div class="profilejumbotron">
	<div id="profilepicture">
		<img src="<%= @user.pic%>" class="circular" />
	</div>
</div>

<div class="profilepagecontainer">
<div class="profileinfo">
	<h1 style="color:white"><%= @user.username.capitalize %></h1>
	<h3 style="color:white"> Lives in <%= @user.zipcode.to_region%> </h3>
	<h4 style="color:white"> Contact: <%= @user.email %></h4>
</div>

<div class="col-md-6 col-md-offset-4" id="profilebio">
	<h1 style="color:white">Bio:</h1> <p style="color:white"><%= @user.bio %></p>
		<h1 style="color:white"><%= @user.username.capitalize %>'s Skills:</h1>
	<ul>
	  <% @user_skill.each do |s| %>
	    <li><h4 style="color:white"><b><%= s.tag.upcase %></b>: <%=s.skill.capitalize%></h4>
	   	</li> 
	  <% end %>
	</ul>
		<h1 style="color:white"><%= @user.username.capitalize %> wants to learn:</h1>
	<ul>
	  <% @user_skill.each do |s| %>
	    <li><h4 style="color:white"><b><%= s.learntag.upcase %></b>: <%=s.tolearn.capitalize %></h4></li>
	  <% end %>
	</ul>
</div>
</div>

</div>

app/views/skills/results.html.erb
<% content_for :body_type do%>
	resultspage
<% end %>

<h1 style="text-align:center">Search Results:</h1>

<div class="resultscontainer">
	<% @skills.each do |s| %>
	<div class= "col-md-6" id="userresults_<%=s[:user_id] %>">
		<div id="resultspic">
			<img src="<%= s.user.pic %>" class="circular" />
		</div>	
		
		<div id="resultsinfo">
			<h1><%= link_to s.user.username, public_profile_path(s.user.id) %></h1>
			<h3><b>Lives in:</b> <%= s.user.zipcode.to_region %></h3>
			<h3><b>Distance:</b> <%= distance_to_zipcode s.user.zipcode %></h3>
			<% s.user.skills.each do |sk| %>
				<h3><b>Skills:</b> <%= sk.skill %></h3>
		</div>
	</div>
			<% end %>
	<% end %>
</div>

app/views/skills/show.html.erb
<h1>Dashboard</h1>
<p>pic</p>
<p>bio</p>
<p>skills</p>
<p>want to learn</p>